### ISSUE TITLE
version check

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [dub-flow/subsnipe#5]
as it is now, the program checks for a new version before running the rest of the logic.

question is whether this should be opt out, executed *after* the main logic, or kept as is.

an option would be to only perform the check when `--version` is called or `version` subcommand is printed.

**Comment by dub-flow** [comment]
Hmm, I'm wary of only executing it if people run `--version` because there isn't a way for me to notify users about updates. So I want to make sure they are aware if there is a new version.

What would be the benefit of the version check being done after the main logic?

Is there a use case where it makes sense NOT to check for an update? If so, we could introduce a flag like `--skip-update-check`.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
I like the arguments, `--skip-update-check` would be great. it saves a GitHub ping every time the program is run.
